import {createAuthClient} from '@neondatabase/auth';import {BetterAuthVanillaAdapter} from '@neondatabase/auth/vanilla/adapters';const BASE='https://ep-snowy-king-b14vtsc9.neonauth.c-5.eu-central-1.aws.neon.tech/neondb/auth';const auth=createAuthClient(BASE,{adapter:BetterAuthVanillaAdapter()});const STORE='asztal.v1.independent';let session=null;let busy=false;const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const local=()=>{try{let a=JSON.parse(localStorage.getItem(STORE)||'[]');return Array.isArray(a)?a:[]}catch{return[]}};
const looksJWT=t=>typeof t==='string'&&t.split('.').length===3;
async function token(){
  let failures=[];
  try{const response=await auth.getSession();const d=response?.data||response;const candidates=[d?.jwt,d?.session?.jwt,d?.session?.accessToken,d?.session?.access_token,d?.accessToken,d?.access_token];const jwt=candidates.find(looksJWT);if(jwt)return jwt;}catch(e){failures.push('session: '+(e?.message||String(e)))}
  try{if(typeof auth.token==='function'){const r=await auth.token();if(r?.error)throw Error(r.error.message||'Token error');const jwt=r?.data?.token||r?.token;if(looksJWT(jwt))return jwt}}catch(e){failures.push('token endpoint: '+(e?.message||String(e)))}
  try{if(typeof auth.getJWTToken==='function'){const jwt=await auth.getJWTToken();if(looksJWT(jwt))return jwt}}catch(e){failures.push('JWT SDK: '+(e?.message||String(e)))}
  throw Error('TOKEN LÉPÉS: Nincs kiadható JWT. '+failures.join(' | '));
}
async function sync(mode){if(busy)return;busy=true;const out=document.getElementById('cloud-status');if(out)out.textContent='Szinkron folyamatban…';try{const t=await token();const opts={headers:{Authorization:'Bearer '+t}};if(mode==='upload'){if(!confirm('A '+local().length+' helyi könyvjelzőt mented a V1 saját felhőjébe? Az ott már meglévő azonosítókat frissítheti.'))return;opts.method='POST';opts.headers['Content-Type']='application/json';opts.body=JSON.stringify({items:local()})}let response;try{response=await fetch('/api/sync',opts)}catch(e){throw Error('API HÁLÓZAT: '+(e?.message||String(e)))}let data;try{data=await response.json()}catch{throw Error('API VÁLASZ: HTTP '+response.status+' (nem JSON)')}if(!response.ok)throw Error('API VÁLASZ: HTTP '+response.status+' – '+(data.error||'Szinkronhiba'));if(mode==='download'){const current=local(),keys=new Set(current.map(x=>x.url?.toLowerCase()+'|'+x.folder?.toLowerCase())),ids=new Set(current.map(x=>x.id));let added=0;for(const x of data.items||[]){let k=x.url?.toLowerCase()+'|'+x.folder?.toLowerCase();if(ids.has(x.id)||keys.has(k))continue;current.push(x);ids.add(x.id);keys.add(k);added++}if(added){localStorage.setItem(STORE,JSON.stringify(current));}alert(added+' új könyvjelző betöltve. A helyi változatokat nem írtuk felül.');if(added)location.reload()}else alert(data.saved+' könyvjelző elmentve a felhőbe.')}catch(e){alert('Felhő: '+e.message)}finally{busy=false;const out=document.getElementById('cloud-status');if(out)out.textContent='A mentés és betöltés kézi, nem automatikus szinkron.'}}
function showAuth(signup=false){let old=document.getElementById('v1-auth-backdrop');if(old)old.remove();const back=document.createElement('div');back.id='v1-auth-backdrop';back.className='auth-overlay';back.innerHTML='<section class="auth-glass" role="dialog" aria-modal="true" aria-labelledby="auth-title"><button class="auth-close" type="button" aria-label="Bezárás">×</button><div class="auth-glyph">✦</div><div class="eyebrow">ASZTAL V1 · SAJÁT FELHŐ</div><h2 id="auth-title">'+(signup?'Fiók létrehozása':'Üdv újra!')+'</h2><p class="muted-text">'+(signup?'Hozz létre saját ASZTAL V1-fiókot.':'Jelentkezz be a saját V1 könyvtáradhoz.')+'</p><form id="v1-auth-form"><label class="field">E-mail-cím<input name="email" type="email" autocomplete="email" placeholder="email@pelda.hu" required></label><label class="field">Jelszó<input name="password" type="password" autocomplete="'+(signup?'new-password':'current-password')+'" minlength="8" placeholder="Legalább 8 karakter" required></label><div id="v1-auth-error" role="alert"></div><button class="btn primary auth-submit" type="submit">'+(signup?'Regisztráció':'Belépés')+'</button></form><button type="button" class="auth-switch">'+(signup?'Már van V1-fiókod? Belépés':'Még nincs V1-fiókod? Regisztráció')+'</button><p class="auth-foot">Az eredeti ASZTAL-fióktól és könyvjelzőktől különálló rendszer.</p></section>';document.body.appendChild(back);back.querySelector('.auth-close').onclick=()=>back.remove();back.onclick=e=>{if(e.target===back)back.remove()};back.querySelector('.auth-switch').onclick=()=>{back.remove();showAuth(!signup)};back.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=back.querySelector('.auth-submit');const error=back.querySelector('#v1-auth-error');const fields=new FormData(e.target);button.disabled=true;button.textContent='Kis türelmet…';error.textContent='';try{const email=String(fields.get('email')).trim(),password=String(fields.get('password'));const result=signup?await auth.signUp.email({email,password,name:email.split('@')[0]}):await auth.signIn.email({email,password});if(result?.error)throw Error(result.error.message||'Sikertelen bejelentkezés');session=(await auth.getSession())?.data;if(!session?.user)throw Error('A regisztráció után ellenőrizd az e-mailedet, majd jelentkezz be.');back.remove();render()}catch(err){error.textContent=err.message||'Nem sikerült a belépés'}finally{button.disabled=false;button.textContent=signup?'Regisztráció':'Belépés'}};back.querySelector('input').focus()}
async function login(signup){showAuth(signup)}
async function refresh(){try{session=(await auth.getSession())?.data}catch{session=null}render()}
function render(){const el=document.getElementById('v1-cloud');if(!el)return;el.innerHTML='<div class="panel"><div class="between"><h3>☁ ASZTAL V1 felhő</h3><span class="badge">'+(session?.user?'Bejelentkezve':'Külön Neon felhő')+'</span></div><p class="muted-text">'+(session?.user?esc(session.user.email):'Csak a V1 saját adatbázisát használja.')+'</p><div class="listline">'+(session?.user?'<button class="btn primary" id="cloud-save">↑ Felhőbe mentés</button><button class="btn" id="cloud-load">↓ Felhőből betöltés</button><button class="btn" id="cloud-out">Kilépés</button>':'<button class="btn primary" id="cloud-in">Belépés</button><button class="btn" id="cloud-up">Regisztráció</button>')+'</div><div id="cloud-status" class="sub">A mentés és betöltés kézi, nem automatikus szinkron.</div></div>';const on=(id,fn)=>{const x=document.getElementById(id);if(x)x.onclick=fn};on('cloud-save',()=>sync('upload'));on('cloud-load',()=>sync('download'));on('cloud-in',()=>login(false));on('cloud-up',()=>login(true));on('cloud-out',async()=>{await auth.signOut();session=null;render()})}
window.addEventListener('asztal-render',render);refresh();